package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// ==========================================
// 1. Aurora Indigo (极光靛青 - 经典科技)
// ==========================================
val AuroraPrimaryLight = Color(0xFF2563EB)
val AuroraOnPrimaryLight = Color(0xFFFFFFFF)
val AuroraPrimaryContainerLight = Color(0xFFDBEAFE)
val AuroraOnPrimaryContainerLight = Color(0xFF1E40AF)
val AuroraSecondaryLight = Color(0xFF0284C7)
val AuroraOnSecondaryLight = Color(0xFFFFFFFF)
val AuroraSecondaryContainerLight = Color(0xFFE0F2FE)
val AuroraOnSecondaryContainerLight = Color(0xFF0369A1)
val AuroraTertiaryLight = Color(0xFF7C3AED)
val AuroraOnTertiaryLight = Color(0xFFFFFFFF)
val AuroraTertiaryContainerLight = Color(0xFFEDE9FE)
val AuroraOnTertiaryContainerLight = Color(0xFF5B21B6)

val AuroraPrimaryDark = Color(0xFF60A5FA)
val AuroraOnPrimaryDark = Color(0xFF003258)
val AuroraPrimaryContainerDark = Color(0xFF1E3A8A)
val AuroraOnPrimaryContainerDark = Color(0xFFDBEAFE)
val AuroraSecondaryDark = Color(0xFF38BDF8)
val AuroraOnSecondaryDark = Color(0xFF003548)
val AuroraSecondaryContainerDark = Color(0xFF075985)
val AuroraOnSecondaryContainerDark = Color(0xFFBAE6FD)
val AuroraTertiaryDark = Color(0xFFA78BFA)
val AuroraOnTertiaryDark = Color(0xFF381E72)
val AuroraTertiaryContainerDark = Color(0xFF4C1D95)
val AuroraOnTertiaryContainerDark = Color(0xFFEDE9FE)

// ==========================================
// 2. Morandi Sunset (落日莫兰迪 - 温暖粉金)
// ==========================================
val SunsetPrimaryLight = Color(0xFFE11D48)
val SunsetOnPrimaryLight = Color(0xFFFFFFFF)
val SunsetPrimaryContainerLight = Color(0xFFFFE4E6)
val SunsetOnPrimaryContainerLight = Color(0xFF881337)
val SunsetSecondaryLight = Color(0xFFF97316)
val SunsetOnSecondaryLight = Color(0xFFFFFFFF)
val SunsetSecondaryContainerLight = Color(0xFFFFEDD5)
val SunsetOnSecondaryContainerLight = Color(0xFF9A3412)
val SunsetTertiaryLight = Color(0xFFD97706)
val SunsetOnTertiaryLight = Color(0xFFFFFFFF)
val SunsetTertiaryContainerLight = Color(0xFFFEF3C7)
val SunsetOnTertiaryContainerLight = Color(0xFF78350F)

val SunsetPrimaryDark = Color(0xFFFB7185)
val SunsetOnPrimaryDark = Color(0xFF4C0519)
val SunsetPrimaryContainerDark = Color(0xFF881337)
val SunsetOnPrimaryContainerDark = Color(0xFFFFE4E6)
val SunsetSecondaryDark = Color(0xFFFB923C)
val SunsetOnSecondaryDark = Color(0xFF431407)
val SunsetSecondaryContainerDark = Color(0xFF9A3412)
val SunsetOnSecondaryContainerDark = Color(0xFFFFEDD5)
val SunsetTertiaryDark = Color(0xFFFBBF24)
val SunsetOnTertiaryDark = Color(0xFF451A03)
val SunsetTertiaryContainerDark = Color(0xFF78350F)
val SunsetOnTertiaryContainerDark = Color(0xFFFEF3C7)

// ==========================================
// 3. Fuji Emerald (富士胶片绿 - 复古清新)
// ==========================================
val FujiPrimaryLight = Color(0xFF059669)
val FujiOnPrimaryLight = Color(0xFFFFFFFF)
val FujiPrimaryContainerLight = Color(0xFFD1FAE5)
val FujiOnPrimaryContainerLight = Color(0xFF064E3B)
val FujiSecondaryLight = Color(0xFF0D9488)
val FujiOnSecondaryLight = Color(0xFFFFFFFF)
val FujiSecondaryContainerLight = Color(0xFFCCFBF1)
val FujiOnSecondaryContainerLight = Color(0xFF134E4A)
val FujiTertiaryLight = Color(0xFF65A30D)
val FujiOnTertiaryLight = Color(0xFFFFFFFF)
val FujiTertiaryContainerLight = Color(0xFFECFCCB)
val FujiOnTertiaryContainerLight = Color(0xFF365314)

val FujiPrimaryDark = Color(0xFF34D399)
val FujiOnPrimaryDark = Color(0xFF022C22)
val FujiPrimaryContainerDark = Color(0xFF064E3B)
val FujiOnPrimaryContainerDark = Color(0xFFD1FAE5)
val FujiSecondaryDark = Color(0xFF2DD4BF)
val FujiOnSecondaryDark = Color(0xFF042F2E)
val FujiSecondaryContainerDark = Color(0xFF134E4A)
val FujiOnSecondaryContainerDark = Color(0xFFCCFBF1)
val FujiTertiaryDark = Color(0xFFA3E635)
val FujiOnTertiaryDark = Color(0xFF1A2E05)
val FujiTertiaryContainerDark = Color(0xFF365314)
val FujiOnTertiaryContainerDark = Color(0xFFECFCCB)

// ==========================================
// 4. Obsidian Gold (黑金轻奢 - 典雅奢华)
// ==========================================
val ObsidianPrimaryLight = Color(0xFFB45309)
val ObsidianOnPrimaryLight = Color(0xFFFFFFFF)
val ObsidianPrimaryContainerLight = Color(0xFFFEF3C7)
val ObsidianOnPrimaryContainerLight = Color(0xFF78350F)
val ObsidianSecondaryLight = Color(0xFF475569)
val ObsidianOnSecondaryLight = Color(0xFFFFFFFF)
val ObsidianSecondaryContainerLight = Color(0xFFE2E8F0)
val ObsidianOnSecondaryContainerLight = Color(0xFF0F172A)
val ObsidianTertiaryLight = Color(0xFFCA8A04)
val ObsidianOnTertiaryLight = Color(0xFFFFFFFF)
val ObsidianTertiaryContainerLight = Color(0xFFFEF9C3)
val ObsidianOnTertiaryContainerLight = Color(0xFF713F12)

val ObsidianPrimaryDark = Color(0xFFFBBF24)
val ObsidianOnPrimaryDark = Color(0xFF451A03)
val ObsidianPrimaryContainerDark = Color(0xFF78350F)
val ObsidianOnPrimaryContainerDark = Color(0xFFFEF3C7)
val ObsidianSecondaryDark = Color(0xFF94A3B8)
val ObsidianOnSecondaryDark = Color(0xFF0F172A)
val ObsidianSecondaryContainerDark = Color(0xFF334155)
val ObsidianOnSecondaryContainerDark = Color(0xFFE2E8F0)
val ObsidianTertiaryDark = Color(0xFFFACC15)
val ObsidianOnTertiaryDark = Color(0xFF3A2002)
val ObsidianTertiaryContainerDark = Color(0xFF713F12)
val ObsidianOnTertiaryContainerDark = Color(0xFFFEF9C3)

// Universal Neutrals (Light)
val NeutralBackgroundLight = Color(0xFFF8FAFC)
val NeutralOnBackgroundLight = Color(0xFF0F172A)
val NeutralSurfaceLight = Color(0xFFFFFFFF)
val NeutralOnSurfaceLight = Color(0xFF0F172A)
val NeutralSurfaceVariantLight = Color(0xFFF1F5F9)
val NeutralOnSurfaceVariantLight = Color(0xFF475569)
val NeutralOutlineLight = Color(0xFFCBD5E1)

// Universal Neutrals (Dark)
val NeutralBackgroundDark = Color(0xFF090D16)
val NeutralOnBackgroundDark = Color(0xFFF8FAFC)
val NeutralSurfaceDark = Color(0xFF111827)
val NeutralOnSurfaceDark = Color(0xFFF8FAFC)
val NeutralSurfaceVariantDark = Color(0xFF1F2937)
val NeutralOnSurfaceVariantDark = Color(0xFF9CA3AF)
val NeutralOutlineDark = Color(0xFF374151)
